fetch_lines:
  cron: "*/2 * * * *"
  class: "FetchLinesWorker"
  queue: default

fetch_daily_weather:
  cron: "15 1,13 * * *"
  class: "FetchDailyWeatherWorker"
  queue: default

fetch_hourly_weather:
  cron: "15 2,8,14,20 * * *"
  class: "FetchHourlyWeatherWorker"
  queue: default

fetch_current_weather:
  cron: "*/30 * * * *"
  class: "FetchCurrentWeatherWorker"
  queue: default